version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run tests
          command: |
            docker  build -t ore . --progress=plain
            docker run ore
